### ISSUE TITLE
nix-shell with development dependencies from package.json

### ISSUE THREAD

**Issue by ollieh** [adnelson/nix-node-packages#24]
I've run `nixfromnpm -f package.json -o ~/Projects/nix-node-packages --dev-depth 1 -r http://mylocalregistry` from `~/Projects/mynodeproject/` and it creates a `default.nix` and `project.nix`, along with adding expressions to `~/Projects/nix-node-packages`. Running `nix-shell` and `nix-build` work. The nix expressions for my project in `~/Projects/nix-node-packages/` have `src = ./.;`, which is obviously incorrect, and results in `nix-build ~/Projects/nix-node-packages/default.nix -A nodePackages.mynodeproject` failing like so:

```
return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open './package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
```

`nix-shell ~/Projects/nix-node-packages/default.nix -A nodePackages.mynodeproject` works, but `nix-shell ~/Projects/nix-node-packages/default.nix -A nodePackages.mynodeproject.env` doesn't work as expected. I expected it to build a node_modules with all my dependences _and devDependencies_, but it only includes normal dependencies, behaving just like the command without `.env`. 

I tried `nix-shell default.nix -A env`, I'm not sure that is the correct command, but I was expecting it would give me dev dependencies, but it doesn't either, it behaves the same as `nix-shell default.nix`.

What is going on, and how do I get an environment with dev dependencies?

Additionally, the `-o outputpath` option doesn't work if you use a trailing slash, it'll add the trailing slash to the path in your `default.nix`.

Would appreciate any help!

**Comment by ollieh** [comment]
Woops, wrong project.
