### ISSUE TITLE
Plaidchat

### ISSUE THREAD

**Issue by dmjio** [adnelson/nix-node-packages#8]
@adnelson, what's the error that it fails with? Also, are you building it on OSX?

**Comment by adnelson** [comment]
I'm building on nixos, but from the looks of it it wouldn't matter. Here's the output of `nix-build /path/to/nix-node-packages -A nodePackages.plaidchat`:

```
these derivations will be built:
  /nix/store/bz1xsmywi6g2i2j41zadmxrn1j672zby-nodejs-4.2.3-plaidchat-2.15.0.drv
building path(s) ‘/nix/store/b9f0gglmny8j9r43aq29w6p1bi5f4a76-nodejs-4.2.3-plaidchat-2.15.0’
setVariables
unpacking sources
unpacking source archive /nix/store/8byf3411bci4s3rgx4yn5di9s8hii7bl-plaidchat-2.15.0.tgz
source root is package
patching sources
patching script interpreter paths in /tmp/nix-build-nodejs-4.2.3-plaidchat-2.15.0.drv-0/package
/tmp/nix-build-nodejs-4.2.3-plaidchat-2.15.0.drv-0/package/run.js: interpreter directive changed from "/usr/bin/env node" to "/nix/store/hfv2jhgp24pgiiya0i1vrhaaslpn66jk-nodejs-4.2.3/bin/node "
/tmp/nix-build-nodejs-4.2.3-plaidchat-2.15.0.drv-0/package/bin/install-webdriver-dependencies.sh: interpreter directive changed from "/usr/bin/env bash" to "/nix/store/fx1kaw6faw8vmpwbhmlhl4agxgb110yw-bash-4.3-p42/bin/bash "
/tmp/nix-build-nodejs-4.2.3-plaidchat-2.15.0.drv-0/package/bin/start-webdriver.sh: interpreter directive changed from "/usr/bin/env bash" to "/nix/store/fx1kaw6faw8vmpwbhmlhl4agxgb110yw-bash-4.3-p42/bin/bash "
/tmp/nix-build-nodejs-4.2.3-plaidchat-2.15.0.drv-0/package/bin/wait-for-selenium.sh: interpreter directive changed from "/usr/bin/env bash" to "/nix/store/fx1kaw6faw8vmpwbhmlhl4agxgb110yw-bash-4.3-p42/bin/bash "
/tmp/nix-build-nodejs-4.2.3-plaidchat-2.15.0.drv-0/package/postinstall.sh: interpreter directive changed from "/usr/bin/env bash" to "/nix/store/fx1kaw6faw8vmpwbhmlhl4agxgb110yw-bash-4.3-p42/bin/bash "
/tmp/nix-build-nodejs-4.2.3-plaidchat-2.15.0.drv-0/package/release.sh: interpreter directive changed from "/usr/bin/env bash" to "/nix/store/fx1kaw6faw8vmpwbhmlhl4agxgb110yw-bash-4.3-p42/bin/bash "
configuring
'node_modules/browserify' -> '/nix/store/gfzrhk5mqfxm83f6d5nnvqqaj8qh9ssl-nodejs-4.2.3-browserify-10.2.6/lib/node_modules/browserify'
'node_modules/commander' -> '/nix/store/yscc14gwczk2rzgaml7wdd7y9y6rq5cd-nodejs-4.2.3-commander-2.9.0/lib/node_modules/commander'
'node_modules/electron-prebuilt' -> '/nix/store/qsyy7md0fgs4qpmmwrzjqmj3rjzr2794-nodejs-4.2.3-electron-prebuilt-0.30.8/lib/node_modules/electron-prebuilt'
'node_modules/favico.js' -> '/nix/store/iw6ddzynsxb4wqd88i1wfmakci0dccvn-nodejs-4.2.3-favico.js-0.3.10/lib/node_modules/favico.js'
'node_modules/flux' -> '/nix/store/z2djfrv93lhhfpw5l44z0jhf1h1r9l1b-nodejs-4.2.3-flux-2.1.1/lib/node_modules/flux'
'node_modules/get-uri' -> '/nix/store/flskar4y3h4f5i51y3akwpbf6i7bn7df-nodejs-4.2.3-get-uri-0.1.4/lib/node_modules/get-uri'
'node_modules/key-mirror' -> '/nix/store/6wgdvyps0h6570186687hdkcgvdqqzzk-nodejs-4.2.3-key-mirror-1.0.1/lib/node_modules/key-mirror'
'node_modules/nw' -> '/nix/store/mqq7yaqny74zc1bp8x342mkz3b7f1235-nodejs-4.2.3-nw-0.12.3/lib/node_modules/nw'
'node_modules/object-assign' -> '/nix/store/43sg49wxkdn392dp8g4fkni265cjb6gw-nodejs-4.2.3-object-assign-3.0.0/lib/node_modules/object-assign'
'node_modules/react' -> '/nix/store/8kk6yp9rvk4zxv9r0jjgl1bfw2r195h4-nodejs-4.2.3-react-0.13.3/lib/node_modules/react'
'node_modules/underscore' -> '/nix/store/s6yljd2w0yqcymhdpjjys7vyhq2dlraj-nodejs-4.2.3-underscore-1.8.3/lib/node_modules/underscore'
building
npm install --registry=http://notaregistry.226ddb1921-plaidchat-2.15.0.derp --fetch-retry-mintimeout=0 --fetch-retry-maxtimeout=10 --fetch-retries=0 --userconfig=/dev/null --nodedir=/nix/store/52izhfdzsf1maa8vry8mi8f08306xh9k-node-sources --production
npm WARN skippingAction Module is inside a symlinked module: not running remove number-is-nan@1.0.0 node_modules/nw/node_modules/download/node_modules/decompress-tar/node_modules/strip-dirs/node_modules/is-integer/node_modules/is-finite/node_modules/number-is-nan
npm WARN skippingAction Module is inside a symlinked module: not running remove pinkie@2.0.1 node_modules/nw/node_modules/download/node_modules/request/node_modules/har-validator/node_modules/pinkie-promise/node_modules/pinkie
npm WARN skippingAction Module is inside a symlinked module: not running remove camelcase@2.0.1 node_modules/nw/node_modules/decompress/node_modules/meow/node_modules/camelcase-keys/node_modules/camelcase
npm WARN skippingAction Module is inside a symlinked module: not running remove map-obj@1.0.1 node_modules/nw/node_modules/decompress/node_modules/meow/node_modules/camelcase-keys/node_modules/map-obj
npm WARN skippingAction Module is inside a symlinked module: not running remove signal-exit@2.1.2 node_modules/nw/node_modules/decompress/node_modules/meow/node_modules/loud-rejection/node_modules/signal-exit
npm WARN skippingAction Module is inside a symlinked module: not running remove hosted-git-info@2.1.4 node_modules/nw/node_modules/decompress/node_modules/meow/node_modules/normalize-package-data/node_modules/hosted-git-info
npm WARN skippingAction Module is inside a symlinked module: not running remove is-builtin-module@1.0.0 node_modules/nw/node_modules/decompress/node_modules/meow/node_modules/normalize-package-data/node_modules/is-builtin-module
npm WARN skippingAction Module is inside a symlinked module: not running remove semver@5.1.0 node_modules/nw/node_modules/decompress/node_modules/meow/node_modules/normalize-package-data/node_modules/semver
npm WARN skippingAction Module is inside a symlinked module: not running remove validate-npm-package-license@3.0.1 node_modules/nw/node_modules/decompress/node_modules/meow/node_modules/normalize-package-data/node_modules/validate-npm-package-license
npm WARN skippingAction Module is inside a symlinked module: not running remove find-up@1.1.0 node_modules/nw/node_modules/decompress/node_modules/meow/node_modules/read-pkg-up/node_modules/find-up
npm WARN skippingAction Module is inside a symlinked module: not running remove read-pkg@1.1.0 node_modules/nw/node_modules/decompress/node_modules/meow/node_modules/read-pkg-up/node_modules/read-pkg
npm WARN skippingAction Module is inside a symlinked module: not running remove indent-string@2.1.0 node_modules/nw/node_modules/decompress/node_modules/meow/node_modules/redent/node_modules/indent-string
npm WARN skippingAction Module is inside a symlinked module: not running remove strip-indent@1.0.1 node_modules/nw/node_modules/decompress/node_modules/meow/node_modules/redent/node_modules/strip-indent

> plaidchat@2.15.0 postinstall /tmp/nix-build-nodejs-4.2.3-plaidchat-2.15.0.drv-0/package
> ./postinstall.sh

+ cp node_modules/electron-prebuilt/dist/libffmpegsumo.so node_modules/nw/nwjs/libffmpegsumo.so
cp: cannot create regular file 'node_modules/nw/nwjs/libffmpegsumo.so': Permission denied

npm WARN plaidchat@2.15.0 No license field.
npm ERR! Linux 3.14.43
npm ERR! argv "/nix/store/hfv2jhgp24pgiiya0i1vrhaaslpn66jk-nodejs-4.2.3/bin/node" "/nix/store/r8jwjgp04x20nacp5509arvfif5lpxis-nodejs-4.2.3-npm-3.5.2/bin/npm" "install" "--registry=http://notaregistry.226ddb1921-plaidchat-2.15.0.derp" "--fetch-retry-mintimeout=0" "--fetch-retry-maxtimeout=10" "--fetch-retries=0" "--userconfig=/dev/null" "--nodedir=/nix/store/52izhfdzsf1maa8vry8mi8f08306xh9k-node-sources" "--production"
npm ERR! node v4.2.3
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! plaidchat@2.15.0 postinstall: `./postinstall.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the plaidchat@2.15.0 postinstall script './postinstall.sh'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the plaidchat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./postinstall.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs plaidchat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls plaidchat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/nix-build-nodejs-4.2.3-plaidchat-2.15.0.drv-0/package/npm-debug.log
NPM installation of plaidchat@2.15.0 failed!
Rerunning with verbose logging:
npm info it worked if it ends with ok
npm verb cli [ '/nix/store/hfv2jhgp24pgiiya0i1vrhaaslpn66jk-nodejs-4.2.3/bin/node',
npm verb cli   '/nix/store/r8jwjgp04x20nacp5509arvfif5lpxis-nodejs-4.2.3-npm-3.5.2/bin/npm',
npm verb cli   'install',
npm verb cli   '.',
npm verb cli   '--registry=http://notaregistry.226ddb1921-plaidchat-2.15.0.derp',
npm verb cli   '--fetch-retry-mintimeout=0',
npm verb cli   '--fetch-retry-maxtimeout=10',
npm verb cli   '--fetch-retries=0',
npm verb cli   '--userconfig=/dev/null',
npm verb cli   '--nodedir=/nix/store/52izhfdzsf1maa8vry8mi8f08306xh9k-node-sources',
npm verb cli   '--production',
npm verb cli   '--loglevel=verbose' ]
npm info using npm@3.5.2
npm info using node@v4.2.3
npm verb config Skipping project config: /tmp/nix-build-nodejs-4.2.3-plaidchat-2.15.0.drv-0/package/.npmrc. (matches userconfig)
npm WARN skippingAction Module is inside a symlinked module: not running remove number-is-nan@1.0.0 node_modules/nw/node_modules/download/node_modules/decompress-tar/node_modules/strip-dirs/node_modules/is-integer/node_modules/is-finite/node_modules/number-is-nan
npm WARN skippingAction Module is inside a symlinked module: not running remove pinkie@2.0.1 node_modules/nw/node_modules/download/node_modules/request/node_modules/har-validator/node_modules/pinkie-promise/node_modules/pinkie
npm WARN skippingAction Module is inside a symlinked module: not running remove camelcase@2.0.1 node_modules/nw/node_modules/decompress/node_modules/meow/node_modules/camelcase-keys/node_modules/camelcase
npm WARN skippingAction Module is inside a symlinked module: not running remove map-obj@1.0.1 node_modules/nw/node_modules/decompress/node_modules/meow/node_modules/camelcase-keys/node_modules/map-obj
npm WARN skippingAction Module is inside a symlinked module: not running remove signal-exit@2.1.2 node_modules/nw/node_modules/decompress/node_modules/meow/node_modules/loud-rejection/node_modules/signal-exit
npm WARN skippingAction Module is inside a symlinked module: not running remove hosted-git-info@2.1.4 node_modules/nw/node_modules/decompress/node_modules/meow/node_modules/normalize-package-data/node_modules/hosted-git-info
npm WARN skippingAction Module is inside a symlinked module: not running remove is-builtin-module@1.0.0 node_modules/nw/node_modules/decompress/node_modules/meow/node_modules/normalize-package-data/node_modules/is-builtin-module
npm WARN skippingAction Module is inside a symlinked module: not running remove semver@5.1.0 node_modules/nw/node_modules/decompress/node_modules/meow/node_modules/normalize-package-data/node_modules/semver
npm WARN skippingAction Module is inside a symlinked module: not running remove validate-npm-package-license@3.0.1 node_modules/nw/node_modules/decompress/node_modules/meow/node_modules/normalize-package-data/node_modules/validate-npm-package-license
npm WARN skippingAction Module is inside a symlinked module: not running remove find-up@1.1.0 node_modules/nw/node_modules/decompress/node_modules/meow/node_modules/read-pkg-up/node_modules/find-up
npm WARN skippingAction Module is inside a symlinked module: not running remove read-pkg@1.1.0 node_modules/nw/node_modules/decompress/node_modules/meow/node_modules/read-pkg-up/node_modules/read-pkg
npm WARN skippingAction Module is inside a symlinked module: not running remove indent-string@2.1.0 node_modules/nw/node_modules/decompress/node_modules/meow/node_modules/redent/node_modules/indent-string
npm WARN skippingAction Module is inside a symlinked module: not running remove strip-indent@1.0.1 node_modules/nw/node_modules/decompress/node_modules/meow/node_modules/redent/node_modules/strip-indent
npm verb lock using /tmp/nix-build-nodejs-4.2.3-plaidchat-2.15.0.drv-0/package/.npm/_locks/staging-21dadfb08da6dc56.lock for /tmp/nix-build-nodejs-4.2.3-plaidchat-2.15.0.drv-0/package/node_modules/.staging
npm verb unlock done using /tmp/nix-build-nodejs-4.2.3-plaidchat-2.15.0.drv-0/package/.npm/_locks/staging-21dadfb08da6dc56.lock for /tmp/nix-build-nodejs-4.2.3-plaidchat-2.15.0.drv-0/package/node_modules/.staging
npm info lifecycle plaidchat@2.15.0~preinstall: plaidchat@2.15.0
npm info linkStuff plaidchat@2.15.0
npm verb linkBins plaidchat@2.15.0
npm verb linkMans plaidchat@2.15.0
npm info lifecycle plaidchat@2.15.0~install: plaidchat@2.15.0
npm info lifecycle plaidchat@2.15.0~postinstall: plaidchat@2.15.0

> plaidchat@2.15.0 postinstall /tmp/nix-build-nodejs-4.2.3-plaidchat-2.15.0.drv-0/package
> ./postinstall.sh

+ cp node_modules/electron-prebuilt/dist/libffmpegsumo.so node_modules/nw/nwjs/libffmpegsumo.so
cp: cannot create regular file 'node_modules/nw/nwjs/libffmpegsumo.so': Permission denied

npm verb lifecycle plaidchat@2.15.0~postinstall: unsafe-perm in lifecycle true
npm verb lifecycle plaidchat@2.15.0~postinstall: PATH: /nix/store/r8jwjgp04x20nacp5509arvfif5lpxis-nodejs-4.2.3-npm-3.5.2/lib/node_modules/npm/bin/node-gyp-bin:/tmp/nix-build-nodejs-4.2.3-plaidchat-2.15.0.drv-0/package/node_modules/.bin:/nix/store/r8jwjgp04x20nacp5509arvfif5lpxis-nodejs-4.2.3-npm-3.5.2/bin:/nix/store/hfv2jhgp24pgiiya0i1vrhaaslpn66jk-nodejs-4.2.3/bin:/nix/store/zvw9brmkdr8687asl6sqig3jmgdf85qb-tree-1.7.0/bin:/nix/store/aps7mdk3g14c76iisll3injydc17qgb4-nodejs-4.2.3-mkdirp-0.5.1/bin:/nix/store/xafn8dwdlhrjgp563llwd2wn5q078zb2-nodejs-4.2.3-rimraf-2.4.4/bin:/nix/store/76ya2zvkkfyk1126v2r1hifk6rmrxcnf-nodejs-4.2.3-semver-5.1.0/bin:/nix/store/fngz7im08a0kj2al0wfhjc0755lzcmpd-nodejs-4.2.3-node-gyp-3.2.1/bin:/nix/store/djk7svnvq0xw9myv78z6v0qj29jk58kh-nodejs-4.2.3-nopt-3.0.6/bin:/nix/store/rmgs396v9p604wn31ylsbilyi91zhcjg-nodejs-4.2.3-har-validator-2.0.3/bin:/nix/store/x42k29hsbyvg9n7m61hasbwv6b8m8abg-nodejs-4.2.3-node-uuid-1.4.7/bin:/nix/store/gmz79hfp5r9ki2rj570s4x4j1hqc047z-nodejs-4.2.3-which-1.2.0/bin:/nix/store/15nls1ld0j186mcnij3km6ai2wm0pivr-nodejs-4.2.3-semver-2.3.2/bin:/nix/store/ccllsn9zwn2mxwdrg5wzsp24gv6b7gf9-nodejs-4.2.3-opener-1.4.1/bin:/nix/store/lm6dyvwkdyrhnabc147j978c95pyzq4z-nodejs-4.2.3-semver-5.0.3/bin:/nix/store/y4f8fr5nqizn5ii9vp5wwj0wwlkmds33-python-2.7.11/bin:/nix/store/3yl1p8yawjvf8ga4yclgzv5cdhrl4wr9-util-linux-2.27.1/bin:/nix/store/1z72dcicw4r87vmcnwbmgdw424nrz58c-patchelf-0.8/bin:/nix/store/n27xxmjjmcvwz5pss08qxz9isdh9mgbd-paxctl-0.9/bin:/nix/store/f3q55vxs9i3zxasnhlf5il0byrg456d2-gcc-wrapper-4.9.3/bin:/nix/store/gfzrhk5mqfxm83f6d5nnvqqaj8qh9ssl-nodejs-4.2.3-browserify-10.2.6/bin:/nix/store/bnmm9yw0qy0fjpvf6k49k2c6lfq7rqwc-nodejs-4.2.3-JSONStream-1.0.7/bin:/nix/store/pg6955jh42xkk0z2hrchqwq2m4n5jvgi-nodejs-4.2.3-browser-pack-5.0.1/bin:/nix/store/3ln8nnn80pcdsj4cp7cxzlnchyr7ic2y-nodejs-4.2.3-umd-3.0.1/bin:/nix/store/bhfgr8q7ra75a0y5prbamc0fxrnbsl5q-nodejs-4.2.3-sha.js-2.4.4/bin:/nix/store/m59qiad5q9hq5p32wia96bq94a84zks8-nodejs-4.2.3-miller-rabin-4.0.0/bin:/nix/store/hpgnbmvyj37kwmm1a8wlg90jm932vdvj-nodejs-4.2.3-deps-sort-1.3.9/bin:/nix/store/3yv78r4fas2y9rsy8qhbdqcg3pd5sf18-nodejs-4.2.3-insert-module-globals-6.6.3/bin:/nix/store/pz6m4v6pvlv5i47fl1nc9jcgsfnvnjbp-nodejs-4.2.3-acorn-1.2.2/bin:/nix/store/qw0y2cbl57fiszygpfrxazka13jcgfs0-nodejs-4.2.3-module-deps-3.9.1/bin:/nix/store/yhgglixcsq6zd2z4w14rvf4xdb2ahcrm-nodejs-4.2.3-parents-1.0.1/bin:/nix/store/qsyy7md0fgs4qpmmwrzjqmj3rjzr2794-nodejs-4.2.3-electron-prebuilt-0.30.8/bin:/nix/store/ddsg50csxpvfcldakdij9kbmfw89l48g-nodejs-4.2.3-electron-download-1.4.1/bin:/nix/store/zfclk6hwqkzh3rx6q0grmvvrlihsr456-nodejs-4.2.3-mkdirp-0.5.1/bin:/nix/store/49crk2lhp17f1as7jcyp9hz14jd71yj0-nodejs-4.2.3-ncp-0.6.0/bin:/nix/store/k9yq50aspr69jr2ishi976s7phj19ab2-nodejs-4.2.3-rimraf-2.2.8/bin:/nix/store/n8aikjfg6ny1ivnhhkjy8bj8lfgrf75a-nodejs-4.2.3-nugget-1.6.0/bin:/nix/store/xbq3vl2ygrggm853mwwplgzxhcm4cr76-nodejs-4.2.3-pretty-bytes-1.0.4/bin:/nix/store/czlfdh1wb9czllz9c6f9w7ilacn0gyji-nodejs-4.2.3-semver-5.1.0/bin:/nix/store/cgqpl53i72nx7rf76imzcy0cv0xnw4hq-nodejs-4.2.3-strip-indent-1.0.1/bin:/nix/store/9cw2zwqxlzbdpyjyq64igaf8amddvqmx-nodejs-4.2.3-har-validator-2.0.5/bin:/nix/store/6v7sddadkzzrlys8s30jpm49adjkfkv4-nodejs-4.2.3-node-uuid-1.4.7/bin:/nix/store/g3bkn7f1gl7irs0bxrbr3yhja1qzshsi-nodejs-4.2.3-rc-1.1.5/bin:/nix/store/j6i0iyap280417758z5zwnlpqwy4bzvw-nodejs-4.2.3-strip-json-comments-1.0.4/bin:/nix/store/a1aq6lb1zxh00ifhk5brcd43mpvbxmqr-nodejs-4.2.3-extract-zip-1.4.1/bin:/nix/store/n0plzz6ld70fx1rnig39b49fy7x60rpv-nodejs-4.2.3-mkdirp-0.5.0/bin:/nix/store/mqq7yaqny74zc1bp8x342mkz3b7f1235-nodejs-4.2.3-nw-0.12.3/bin:/nix/store/zy2rqlspav9ff32dmx5pb9aycid3bdb6-nodejs-4.2.3-has-ansi-1.0.3/bin:/nix/store/2i1q0r5n27i6d1mmcs4gi73i75429icf-nodejs-4.2.3-strip-ansi-2.0.1/bin:/nix/store/a8chqscq9d0bkxi9b5c41q00mlmx9xdj-nodejs-4.2.3-supports-color-1.3.1/bin:/nix/store/6d8kmsvcz99lrc69yxkypf87d1q44ja1-nodejs-4.2.3-decompress-2.3.0/bin:/nix/store/i9zrb5cxnyl340c490sr0cypm7p3ygzj-nodejs-4.2.3-strip-dirs-1.1.1/bin:/nix/store/isq51vq50494l1qca8brgvknannsnnhw-nodejs-4.2.3-seek-bzip-1.0.5/bin:/nix/store/wk3b4c5mm1f3254fw0jlcfxyvjva8szg-nodejs-4.2.3-strip-bom-1.0.0/bin:/nix/store/qb5nkmzlsdzzcpdsmpa3g8hfxcpc40qw-nodejs-4.2.3-download-3.3.0/bin:/nix/store/s8kxinah9nzl4knp53w9kbpy1dnzd3nv-nodejs-4.2.3-strip-dirs-0.1.1/bin:/nix/store/h49s0rc3yfiph89yhg6njws9nvlngqd5-nodejs-4.2.3-has-ansi-0.1.0/bin:/nix/store/4jz4wmjzzazcjv5cvvdqnjxpcszja2mj-nodejs-4.2.3-strip-ansi-0.3.0/bin:/nix/store/sh5p0fjzjs1shjyhzv8alaqhavydq0q8-nodejs-4.2.3-supports-color-0.2.0/bin:/nix/store/w16fbrw2r2xg9prby3bn1raypkk2cc2p-nodejs-4.2.3-lpad-align-1.1.0/bin:/nix/store/plzv3j012rqs649ynx6wm5lybdk43236-nodejs-4.2.3-indent-string-1.2.2/bin:/nix/store/9dqa50ad9kpz8jmnhkj3yik1j5kx1x2k-nodejs-4.2.3-repeating-1.1.3/bin:/nix/store/q6d0wc8dbvq9pd2w5appylhpdr4isljn-nodejs-4.2.3-rc-0.5.5/bin:/nix/store/madqpy59935fm5grkqgajdjwgia8fjwb-nodejs-4.2.3-strip-json-comments-0.1.3/bin:/nix/store/474x1nisfr1im9adhpxyfs6855xf8095-nodejs-4.2.3-rimraf-2.4.4/bin:/nix/store/ydi7z9bslxx9bmvgk5s4m0b8qhc2kwli-nodejs-4.2.3-semver-4.3.6/bin:/nix/store/4bc877fylwi6ahalspn89slxdizhpp2z-nodejs-4.2.3-window-size-0.1.4/bin:/nix/store/1wfwivyyfp6czha6xksiyd3r99zca3vi-nodejs-4.2.3-envify-3.4.0/bin:/nix/store/9cnmzw07mgpf584yzsrkdh1i7m1yf2mp-nodejs-4.2.3-esprima-fb-13001.1001.0-dev-harmony-fb/bin:/nix/store/1bwrkqji9jsq0ypip3cpgz5qcn2rad55-coreutils-8.24/bin:/nix/store/05z0y2c87p4z0gcn9wlyxskg5kcyjxmy-findutils-4.4.2/bin:/nix/store/l489hcmi1la2qj5px08g1bszijm9z1hm-diffutils-3.3/bin:/nix/store/s1qfi4hrxvs8bqs148haisgcxzvf2cjy-gnused-4.2.2/bin:/nix/store/vk8b9m1pnlv3vf9l4wnak9grxp5j3c55-gnugrep-2.22/bin:/nix/store/bsiqv3v9dcijgd275fglxxi93a1mfm9w-gawk-4.1.3/bin:/nix/store/60zf1xjmhwbf4g42724wrrj6ydy45cch-gnutar-1.28/bin:/nix/store/nag704c7wqqyv3n86i8zs3b66sgpq02q-gzip-1.6/bin:/nix/store/xx0lhx08rxin0w20j0y7ib4lkvl72vw4-bzip2-1.0.6/bin:/nix/store/zym9b3asfqcyhllrz2r8lzh6ir62ll1s-gnumake-4.1/bin:/nix/store/fx1kaw6faw8vmpwbhmlhl4agxgb110yw-bash-4.3-p42/bin:/nix/store/mqd6mwww0zi14zjnh6pcvb4wr03z8q9g-patch-2.7.5/bin:/nix/store/gnvv792j5jb7xzzjpp602ihs2y5ffjbv-xz-5.2.2/bin:/nix/store/rpdv6pi9z5dq7mcfh3rsavx0aixvcgl1-gcc-4.9.3/bin:/nix/store/3wjska842abcj7k36jnk5233i2x83c66-binutils-2.23.1/bin:/nix/store/jlmb88f5hgigbmc3c74ynxgn3frlzxkr-glibc-2.21/bin:/nix/store/1bwrkqji9jsq0ypip3cpgz5qcn2rad55-coreutils-8.24/bin
npm verb lifecycle plaidchat@2.15.0~postinstall: CWD: /tmp/nix-build-nodejs-4.2.3-plaidchat-2.15.0.drv-0/package
npm info lifecycle plaidchat@2.15.0~postinstall: Failed to exec postinstall script
npm WARN plaidchat@2.15.0 No license field.
npm verb stack Error: plaidchat@2.15.0 postinstall: `./postinstall.sh`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/nix/store/r8jwjgp04x20nacp5509arvfif5lpxis-nodejs-4.2.3-npm-3.5.2/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at EventEmitter.emit (events.js:172:7)
npm verb stack     at ChildProcess.<anonymous> (/nix/store/r8jwjgp04x20nacp5509arvfif5lpxis-nodejs-4.2.3-npm-3.5.2/lib/node_modules/npm/lib/utils/spawn.js:24:14)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at ChildProcess.emit (events.js:172:7)
npm verb stack     at maybeClose (internal/child_process.js:818:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm verb pkgid plaidchat@2.15.0
npm verb cwd /tmp/nix-build-nodejs-4.2.3-plaidchat-2.15.0.drv-0/package
npm ERR! Linux 3.14.43
npm ERR! argv "/nix/store/hfv2jhgp24pgiiya0i1vrhaaslpn66jk-nodejs-4.2.3/bin/node" "/nix/store/r8jwjgp04x20nacp5509arvfif5lpxis-nodejs-4.2.3-npm-3.5.2/bin/npm" "install" "." "--registry=http://notaregistry.226ddb1921-plaidchat-2.15.0.derp" "--fetch-retry-mintimeout=0" "--fetch-retry-maxtimeout=10" "--fetch-retries=0" "--userconfig=/dev/null" "--nodedir=/nix/store/52izhfdzsf1maa8vry8mi8f08306xh9k-node-sources" "--production" "--loglevel=verbose"
npm ERR! node v4.2.3
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! plaidchat@2.15.0 postinstall: `./postinstall.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the plaidchat@2.15.0 postinstall script './postinstall.sh'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the plaidchat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./postinstall.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs plaidchat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls plaidchat
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/nix-build-nodejs-4.2.3-plaidchat-2.15.0.drv-0/package/npm-debug.log
builder for ‘/nix/store/bz1xsmywi6g2i2j41zadmxrn1j672zby-nodejs-4.2.3-plaidchat-2.15.0.drv’ failed with exit code 1
error: build of ‘/nix/store/bz1xsmywi6g2i2j41zadmxrn1j672zby-nodejs-4.2.3-plaidchat-2.15.0.drv’ failed
```

The problem area as I see it is this:

```
> plaidchat@2.15.0 postinstall /tmp/nix-build-nodejs-4.2.3-plaidchat-2.15.0.drv-0/package
> ./postinstall.sh

+ cp node_modules/electron-prebuilt/dist/libffmpegsumo.so node_modules/nw/nwjs/libffmpegsumo.so
cp: cannot create regular file 'node_modules/nw/nwjs/libffmpegsumo.so': Permission denied
```

It looks like it's trying to modify its `nw` dependency, adding in the `so` file that `electron-prebuilt` had built. Who the hell knows why; maybe this line could simply be removed from `postinstall.sh` but I'm not sure.

**Comment by dmjio** [comment]
Seems like a permissions error, would it matter if we called `nix-build` with `sudo` ?

**Comment by adnelson** [comment]
No, it's trying to copy something into `node_modules/nw/nwjs` which is a read-only folder in the nix store. Also, there should never be a need to `sudo` any nix commands (other than initial nix installation and `nixos` commands) 

In this particular case the solution might be to do a copy of that `nw` folder rather than symlink it. This could be done as a `preConfigure` step, since the `configurePhase` does all of the symlinking. Something along the lines of adding the following argument to the call to `buildNodePackage`:

```
preConfigure = ''
  mkdir -p node_modules
  cp -r ${nw_0-12-3}/lib/node_modules/nw node_modules/nw
  chmod -R +w node_modules/nw
''
```

But of course, I'm not sure if this will solve the issue

**Comment by dmjio** [comment]
@adnelson, can we point the derivation to build from this branch? 
https://github.com/plaidchat/plaidchat/compare/plaidchat:047acf3...plaidchat:92f6b17

@twolfson made a patch here
https://github.com/plaidchat/plaidchat/issues/147

**Comment by adnelson** [comment]
So I tried building against that branch, and the same thing is happening because it still tries to do a `cp` :disappointed:

**Comment by dmjio** [comment]
@adnelson is `cp` the problem though? Or the lack of folder existence? I see this error at times,

```
cp: cannot stat 'node_modules/electron-prebuilt/dist/libffmpegsumo.so': No such file or directory
```

@adnelson can you paste the latest error?

**Comment by adnelson** [comment]
So I got it to build by putting in a `preConfigure` step like the one I had described. However, the executable `plaidchat` fails to run, because it's assuming the existence of a `node_modules/.bin/nw` executable. And even if I link this to `node_modules/nw/bin/nw`, that thing throws an error itself. This will probably take a bit of debugging to get to work. One of the problems is that in my experience, node packages tend to do _a lot_ of heinous, ugly shit at runtime. For example this gem, in the aforementioned `nw` package:

``` javascript
#!/nix/store/vk13mnlwwsywj4ay0a0p04qalhl26ays-nodejs-4.2.3/bin/node 

function run() {
  // Rename nw.js's own package.json as workaround for https://github.com/nwjs/nw.js/issues/1503
  var packagejson = path.resolve(__dirname, '..', 'package.json');
  var packagejsonBackup = path.resolve(__dirname, '..', 'package_backup.json');
  if (!fs.existsSync(packagejsonBackup)) {
    try {
      fs.renameSync(packagejson, packagejsonBackup);
    } catch (err) {}
  }

  // copy over any asset files (icons, etc) specified via CLI args:
  require('../lib/app_assets').copyAssets(process.platform, bin);
 ....
```

Gotta love it when calling an executable causes a package to attempt to _rename one of its own files_... :rage1:

**Comment by dmjio** [comment]
yea, I'm confused now. This means that plaidchat won't install _at all_ then. Correct?

**Comment by adnelson** [comment]
Not without some modification. It should be possible to patch it to stop the bad behavior.
